Repository DNNCommunity/DNN.Announcements, pull requests merged in 2020-07, with the labels that each got.

#55 Removed contributors in readme
  README.md
Labels: documentation

#52 Ensure ModuleInfo for correct tab is used if module is shared
  Components/Settings/Settings.cs
Labels: bug

#56 Fixes an issue where a single announcement was indexed
  Components/Business/AnnouncementsController.cs
Labels: bug

#57 bumps version to 7.2.3 for next release
  AssemblyInfo.cs
  DotNetNuke.Announcements.dnn
  Properties/AssemblyInfo.cs
Labels: build

#58 Release/7.2.3
  AssemblyInfo.cs
  Components/Business/AnnouncementsController.cs
  Components/Settings/Settings.cs
  DotNetNuke.Announcements.dnn
  Properties/AssemblyInfo.cs
  README.md
Labels: build
